base_url = "https://daltongoo.github.io/"

compile_sass = true
minify_html = true

build_search_index = true

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-dark"
smart_punctuation = true
